# Generated by Django 4.2.3 on 2024-05-18 00:21

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[utils.validators.validate_fields],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[utils.validators.validate_fields],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        validators=[utils.validators.validate_fields],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=200,
                        validators=[utils.validators.validate_fields],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=200,
                        validators=[utils.validators.validate_fields],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            utils.validators.validate_if_is_not_blank,
                            utils.validators.validate_fields_with_200,
                            utils.validators.validate_title_with_two_words,
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[utils.validators.validate_if_is_not_blank]
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_format],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="news.user",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="news",
                        to="news.category",
                        validators=[utils.validators.validate_if_is_not_blank],
                    ),
                ),
            ],
        ),
    ]
