# Generated by Django 4.2.3 on 2024-05-18 00:23

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(
                validators=[utils.validators.validate_date_format]
            ),
        ),
    ]
