# Generated by Django 4.2.3 on 2024-05-17 00:16

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200, validators=[utils.validators.validate_name]
            ),
        ),
    ]
