# Generated by Django 4.2.3 on 2024-05-18 02:37

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    utils.validators.validate_if_is_not_blank,
                    utils.validators.validate_fields_with_200,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=200,
                validators=[
                    utils.validators.validate_if_is_not_blank,
                    utils.validators.validate_fields_with_200,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    utils.validators.validate_if_is_not_blank,
                    utils.validators.validate_fields_with_200,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=200,
                validators=[
                    utils.validators.validate_if_is_not_blank,
                    utils.validators.validate_fields_with_200,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                max_length=200,
                validators=[
                    utils.validators.validate_if_is_not_blank,
                    utils.validators.validate_fields_with_200,
                ],
            ),
        ),
    ]
